export const demoProjects = [
  {
    id: 1,
    ngoName: "Mulheres Que Codam",
    ngoWallet: "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF",
    title: "Mulheres Que Codam - Edição 2",
    description:
      "Formação em programação, mentoria e empregabilidade para mulheres que desejam iniciar ou fortalecer sua trajetória na tecnologia.",
    taxCategory: "Educação e tecnologia",
    targetXlm: 8000,
    raisedXlm: 4200,
    status: "APPROVED",
    metadataUri: "mqc-edicao-2-educacao-tecnologia",
    createdAt: "2026-05-01T12:00:00.000Z",
  },
  {
    id: 2,
    ngoName: "Elo.me",
    ngoWallet: "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF",
    title: "Elo.me - Rede de Mentoria",
    description:
      "Rede de apoio para conectar mulheres em início de carreira a mentoras, trilhas de aprendizagem e oportunidades no ecossistema digital.",
    taxCategory: "Educação e inclusão",
    targetXlm: 6500,
    raisedXlm: 2100,
    status: "APPROVED",
    metadataUri: "elo-me-mentoria-inclusao",
    createdAt: "2026-05-03T12:00:00.000Z",
  },
  {
    id: 3,
    ngoName: "StellarBridge",
    ngoWallet: "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF",
    title: "StellarBridge",
    description:
      "Trilha introdutória sobre finanças digitais, carteiras Stellar e uso responsável de tecnologias descentralizadas em projetos comunitários.",
    taxCategory: "Tokenização e educação financeira",
    targetXlm: 7200,
    raisedXlm: 3600,
    status: "APPROVED",
    metadataUri: "stellarbridge-tokenizacao-educacao-financeira",
    createdAt: "2026-05-05T12:00:00.000Z",
  },
  {
    id: 4,
    ngoName: "Karn",
    ngoWallet: "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF",
    title: "Karn - Gestão de Impacto",
    description:
      "Ferramenta para apoiar organizações sociais na organização de indicadores, prestação de contas e acompanhamento de resultados.",
    taxCategory: "Transparência e gestão",
    targetXlm: 9000,
    raisedXlm: 2900,
    status: "APPROVED",
    metadataUri: "karn-transparencia-gestao-impacto",
    createdAt: "2026-05-07T12:00:00.000Z",
  },
  {
    id: 5,
    ngoName: "Vizinhança Cuidadora",
    ngoWallet: "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF",
    title: "Vizinhança Cuidadora",
    description:
      "Iniciativa comunitária que usa tecnologia para mapear necessidades locais, fortalecer redes de cuidado e aproximar pessoas de serviços essenciais.",
    taxCategory: "Impacto social e saúde",
    targetXlm: 7800,
    raisedXlm: 5100,
    status: "APPROVED",
    metadataUri: "vizinhanca-cuidadora-saude-comunidade",
    createdAt: "2026-05-09T12:00:00.000Z",
  },
  {
    id: 6,
    ngoName: "Mulheres Que Codam",
    ngoWallet: "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF",
    title: "Web3 Liderança",
    description:
      "Programa de liderança para mulheres que querem criar, gerir e comunicar projetos com base em tecnologias Web3 e impacto social.",
    taxCategory: "Educação Web3",
    targetXlm: 8500,
    raisedXlm: 4700,
    status: "APPROVED",
    metadataUri: "web3-lideranca-educacao",
    createdAt: "2026-05-11T12:00:00.000Z",
  },
  {
    id: 8,
    ngoName: "Mulheres Que Codam",
    ngoWallet: "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF",
    title: "Formação Mulheres em Tecnologia",
    description:
      "Ciclo de formação continuada com aulas práticas, acompanhamento pedagógico e suporte para mulheres em transição de carreira.",
    taxCategory: "Educação e empregabilidade",
    targetXlm: 10000,
    raisedXlm: 6300,
    status: "APPROVED",
    metadataUri: "formacao-mulheres-tecnologia-empregabilidade",
    createdAt: "2026-05-13T12:00:00.000Z",
  },
] as const;
