const defaultDemoCurrencies = ["USDGLO", "USDC", "PIX", "BRZ"] as const;
const demoNetwork = "CELO";
const demoPrimaryAsset = "USDGLO";
const demoWalletAddress = "0x228cbC1d913A463a9dC4D353AC9b5FdcfC1c71Cb";
const demoPixKey = "62.977.919/0001-97";

export const demoProjects = [
  {
    id: 1,
    ngoName: "Mulheres Que Codam",
    ngoWallet: demoWalletAddress,
    walletAddress: demoWalletAddress,
    network: demoNetwork,
    primaryAsset: demoPrimaryAsset,
    acceptedAssets: defaultDemoCurrencies,
    pixKey: demoPixKey,
    pixQrCodeUrl: null,
    title: "Mulheres Que Codam - Formação em Tecnologia",
    description:
      "Formação em programação, letramento digital e qualificação profissional para mulheres que desejam iniciar ou fortalecer sua trajetória na tecnologia.",
    taxCategory: "Educação de qualidade",
    eixoTematico: "Educação de qualidade",
    ods: [4, 5, 8],
    odsNames: [
      "ODS 4 - Educação de qualidade",
      "ODS 5 - Igualdade de gênero",
      "ODS 8 - Trabalho decente e crescimento econômico",
    ],
    moedaPrincipal: "USDGLO",
    moedasAceitas: defaultDemoCurrencies,
    targetXlm: 8000,
    raisedXlm: 0,
    status: "APPROVED",
    metadataUri: "mqc-formacao-tecnologia-ods-4-5-8",
    createdAt: "2026-05-01T12:00:00.000Z",
  },
  {
    id: 2,
    ngoName: "Elo.me",
    ngoWallet: demoWalletAddress,
    walletAddress: demoWalletAddress,
    network: demoNetwork,
    primaryAsset: demoPrimaryAsset,
    acceptedAssets: defaultDemoCurrencies,
    pixKey: demoPixKey,
    pixQrCodeUrl: null,
    title: "Elo.me - Rede de Proteção e Mentoria",
    description:
      "Rede de apoio para conectar mulheres em início de carreira a mentoras, trilhas de empregabilidade, proteção social e autonomia econômica.",
    taxCategory: "Equidade de gênero",
    eixoTematico: "Equidade de gênero",
    ods: [5, 8, 10],
    odsNames: [
      "ODS 5 - Igualdade de gênero",
      "ODS 8 - Trabalho decente e crescimento econômico",
      "ODS 10 - Redução das desigualdades",
    ],
    moedaPrincipal: "USDGLO",
    moedasAceitas: defaultDemoCurrencies,
    targetXlm: 6500,
    raisedXlm: 0,
    status: "APPROVED",
    metadataUri: "elo-me-equidade-genero-ods-5-8-10",
    createdAt: "2026-05-03T12:00:00.000Z",
  },
  {
    id: 3,
    ngoName: "Ponte Produtiva",
    ngoWallet: demoWalletAddress,
    walletAddress: demoWalletAddress,
    network: demoNetwork,
    primaryAsset: demoPrimaryAsset,
    acceptedAssets: defaultDemoCurrencies,
    pixKey: demoPixKey,
    pixQrCodeUrl: null,
    title: "Trilhas de Inclusão Produtiva",
    description:
      "Capacitação em finanças digitais, inovação e empreendedorismo para ampliar renda, empregabilidade e participação de mulheres na economia digital.",
    taxCategory: "Inclusão produtiva",
    eixoTematico: "Inclusão produtiva",
    ods: [8, 9, 10],
    odsNames: [
      "ODS 8 - Trabalho decente e crescimento econômico",
      "ODS 9 - Indústria, inovação e infraestrutura",
      "ODS 10 - Redução das desigualdades",
    ],
    moedaPrincipal: "USDGLO",
    moedasAceitas: defaultDemoCurrencies,
    targetXlm: 7200,
    raisedXlm: 0,
    status: "APPROVED",
    metadataUri: "trilhas-inclusao-produtiva-ods-8-9-10",
    createdAt: "2026-05-05T12:00:00.000Z",
  },
  {
    id: 4,
    ngoName: "Karn",
    ngoWallet: demoWalletAddress,
    walletAddress: demoWalletAddress,
    network: demoNetwork,
    primaryAsset: demoPrimaryAsset,
    acceptedAssets: defaultDemoCurrencies,
    pixKey: demoPixKey,
    pixQrCodeUrl: null,
    title: "Karn - Energia Comunitária",
    description:
      "Ferramenta para apoiar comunidades periféricas no planejamento de energia limpa, acesso energético e indicadores de sustentabilidade territorial.",
    taxCategory: "Transição energética justa",
    eixoTematico: "Transição energética justa",
    ods: [7, 9, 10],
    odsNames: [
      "ODS 7 - Energia limpa e acessível",
      "ODS 9 - Indústria, inovação e infraestrutura",
      "ODS 10 - Redução das desigualdades",
    ],
    moedaPrincipal: "USDGLO",
    moedasAceitas: defaultDemoCurrencies,
    targetXlm: 9000,
    raisedXlm: 0,
    status: "APPROVED",
    metadataUri: "karn-transicao-energetica-ods-7-9-10",
    createdAt: "2026-05-07T12:00:00.000Z",
  },
  {
    id: 5,
    ngoName: "Vizinhança Cuidadora",
    ngoWallet: demoWalletAddress,
    walletAddress: demoWalletAddress,
    network: demoNetwork,
    primaryAsset: demoPrimaryAsset,
    acceptedAssets: defaultDemoCurrencies,
    pixKey: demoPixKey,
    pixQrCodeUrl: null,
    title: "Vizinhança Cuidadora - Segurança Alimentar",
    description:
      "Iniciativa comunitária que usa tecnologia para mapear necessidades locais, combater a fome e ampliar o acesso a alimentos de qualidade.",
    taxCategory: "Segurança alimentar",
    eixoTematico: "Segurança alimentar",
    ods: [2, 10],
    odsNames: [
      "ODS 2 - Fome zero e agricultura sustentável",
      "ODS 10 - Redução das desigualdades",
    ],
    moedaPrincipal: "USDGLO",
    moedasAceitas: defaultDemoCurrencies,
    targetXlm: 7800,
    raisedXlm: 0,
    status: "APPROVED",
    metadataUri: "vizinhanca-cuidadora-seguranca-alimentar-ods-2-10",
    createdAt: "2026-05-09T12:00:00.000Z",
  },
  {
    id: 6,
    ngoName: "Mulheres Que Codam",
    ngoWallet: demoWalletAddress,
    walletAddress: demoWalletAddress,
    network: demoNetwork,
    primaryAsset: demoPrimaryAsset,
    acceptedAssets: defaultDemoCurrencies,
    pixKey: demoPixKey,
    pixQrCodeUrl: null,
    title: "Web3 Liderança para Mulheres",
    description:
      "Programa de liderança para mulheres que querem criar, gerir e comunicar projetos de impacto com autonomia econômica e combate à desigualdade.",
    taxCategory: "Equidade de gênero",
    eixoTematico: "Equidade de gênero",
    ods: [5, 8, 10],
    odsNames: [
      "ODS 5 - Igualdade de gênero",
      "ODS 8 - Trabalho decente e crescimento econômico",
      "ODS 10 - Redução das desigualdades",
    ],
    moedaPrincipal: "USDGLO",
    moedasAceitas: defaultDemoCurrencies,
    targetXlm: 8500,
    raisedXlm: 0,
    status: "APPROVED",
    metadataUri: "web3-lideranca-equidade-genero-ods-5-8-10",
    createdAt: "2026-05-11T12:00:00.000Z",
  },
  {
    id: 8,
    ngoName: "Mulheres Que Codam",
    ngoWallet: demoWalletAddress,
    walletAddress: demoWalletAddress,
    network: demoNetwork,
    primaryAsset: demoPrimaryAsset,
    acceptedAssets: defaultDemoCurrencies,
    pixKey: demoPixKey,
    pixQrCodeUrl: null,
    title: "Formação Mulheres em Tecnologia",
    description:
      "Ciclo de educação de qualidade com aulas práticas, acompanhamento pedagógico e suporte para mulheres em transição de carreira.",
    taxCategory: "Educação de qualidade",
    eixoTematico: "Educação de qualidade",
    ods: [4, 8, 9],
    odsNames: [
      "ODS 4 - Educação de qualidade",
      "ODS 8 - Trabalho decente e crescimento econômico",
      "ODS 9 - Indústria, inovação e infraestrutura",
    ],
    moedaPrincipal: "USDGLO",
    moedasAceitas: defaultDemoCurrencies,
    targetXlm: 10000,
    raisedXlm: 0,
    status: "APPROVED",
    metadataUri: "formacao-mulheres-tecnologia-ods-4-8-9",
    createdAt: "2026-05-13T12:00:00.000Z",
  },
] as const;
