import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "from-blue-600",
    "to-indigo-900",
    "from-orange-400",
    "to-red-600",
    "from-emerald-400",
    "to-teal-700",
    "from-purple-500",
    "to-indigo-800",
    "from-rose-400",
    "to-pink-600",
    "from-yellow-400",
    "to-orange-500",
    "from-blue-300",
    "to-blue-600",
    "from-indigo-600",
    "to-purple-900",
    "from-sky-300",
    "to-blue-500",
    "from-slate-800",
    "to-black",
    "from-pink-400",
    "to-rose-600",
    "from-teal-500",
    "to-emerald-800",
    "from-orange-300",
    "to-orange-600",
    "from-blue-800",
    "to-slate-900",
    "from-emerald-500",
    "to-green-800",
    "bg-[#002B99]",
    "bg-orange-500",
    "bg-emerald-500",
    "bg-purple-600",
    "bg-rose-500",
    "bg-yellow-500",
    "bg-blue-400",
    "bg-indigo-700",
    "bg-sky-500",
    "bg-slate-900",
    "bg-pink-500",
    "bg-teal-600",
    "bg-orange-400",
    "bg-blue-900",
    "bg-emerald-600",
    "bg-slate-800",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#0f00a1",
        secondary: "#ff5c00",
        accent: "#ffca00",
        dark: "#0e0f14",
        "background-light": "#FFFF",
        "background-dark": "#070039",
        "surface-light": "#fff2de",
        "surface-dark": "#1F2937",
      },
      fontFamily: {
        display: ["Montserrat", "sans-serif"],
        body: ["Manrope", "sans-serif"],
      },
      animation: {
        marquee: "marquee 40s linear infinite",
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
    },
  },
  plugins: [],
};
export default config;
